/**
 * 
 */
package com.easyJ.j;

/**
 * @author khan.m
 *
 */
public enum JExpressionType {
	NONE, SUPERCLASS, INTERFACE, CLASS, FILTER, GET, 
	FILE_EXT, KEY_SUPERCLASS, KEY_CLASS, KEY_INTERFACE,
	VALUE_SUPERCLASS, VALUE_INTERFACE, VALUE_CLASS,
	FILE_NAME, FILE_CONTENT;
}
